
service: myservice

plugins:  
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs4.3
  region: us-west-2
  stage: dev

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
